version: '2'
services:

  node:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8004:80'
    volumes:
      - ./:/code
    # command: nodemon --use_strict --watch /code/src --legacy-watch -e js,jade,html,jsx /code/src/entrypoint
    command: node /code/src/entrypoint
